version: '3.0'
services:
  haste-server:
    build: .
    environment:
      - STORAGE_TYPE=file
      - STORAGE_FILE_PATH=/app/pastes
    ports:
      - "7777:7777"
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./about.md:/app/about.md
      - "./data:/app/pastes"
